import {
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  FETCH_CAT_REQUEST,
  fetchCat,
  DELETE_CAT_REQUEST,
  DELETE_CAT_SUCCESS,
  DELETE_CAT_ERROR,
  deleteCat
} from './cats'

import {
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  FETCH_DOG_REQUEST,
  fetchDog,
  DELETE_DOG_REQUEST,
  DELETE_DOG_SUCCESS,
  DELETE_DOG_ERROR,
  deleteDog
} from './dogs'

export {
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  FETCH_CAT_REQUEST,
  fetchCat,
  DELETE_CAT_REQUEST,
  DELETE_CAT_SUCCESS,
  DELETE_CAT_ERROR,
  deleteCat
}

export {
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  FETCH_DOG_REQUEST,
  fetchDog,
  DELETE_DOG_REQUEST,
  DELETE_DOG_SUCCESS,
  DELETE_DOG_ERROR,
  deleteDog
}